name: repique_release_go1.15

on:
  workflow_dispatch:
   inputs:
    tag:
     description: 'Tag'
     required: true
     default: 'v1.1.0'
    tagv2:
     description: 'TagV2'
     required: true
     default: 'Ver. 2.1.X'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'repique-release-golang1.15'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: 1.15
    
    - name: Create Release Folder
      run: |
        mkdir release

    - name: Build Win64
      run: make GOARCH=amd64 GOOS=windows CGO_ENABLED=0

    - id: sha2win
      run: |
        echo "::set-output name=VALUE::$(sha256sum './bin/repique.exe' | sed '/ /s/ .*//')"
      
    - name: SHA-2 windows_amd64
      uses: RubbaBoy/BYOB@v1.2.0
      with:
        NAME: repique115pe
        LABEL: 'SHA-256 latest repique.exe golang 1.15'
        STATUS: ${{ steps.sha2win.outputs.VALUE }}
        COLOR: blue
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy examples of configuration
      run: cp ./examples/configuration/* ./bin

    - name: Zip Win64
      uses: edgarrc/action-7z@v1.0.4
      with:
        args: 7z a ./release/repique_windows_amd64.zip -r ./bin/* -mm=LZMA -mx=9 -md=32m

    - name: Clean Win64
      run: rm -rf ./bin
   
    - name: Build Linux64
      run: make GOARCH=amd64 GOOS=linux CGO_ENABLED=0

    - id: sha2lin
      run: |
        echo "::set-output name=VALUE::$(sha256sum './bin/repique' | sed '/ /s/ .*//')"

    - name: SHA-2 linux_amd64
      uses: RubbaBoy/BYOB@v1.2.0
      with:
        NAME: repique115elf
        LABEL: 'SHA-256 latest repique golang 1.15'
        STATUS: ${{ steps.sha2lin.outputs.VALUE }}
        COLOR: blue
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy examples of configuration
      run: cp ./examples/configuration/* ./bin

    - name: Tar Linux64
      run: tar czf ./release/repique_linux_amd64.tar.gz -C ./bin . 

    - uses: "AZ-X/action-automatic-releases@master"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag	: ${{ github.event.inputs.tag }}
          title: Repique Release ${{ github.event.inputs.tagv2 }} golang 1.15
          prerelease: false
          files: |
            ./release/*.zip
            ./release/*.tar.gz
